FNSWeb/Controllers/TeacherMasterController.cs
using BLL;
using Core;
using DAL;
using FNSWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace FNSWeb.Controllers
{
    [SessionAuthorize]
    public class TeacherMasterController : Controller
    {
        private IRepository<Teacher> _repositoryTeacher;
        private IRepository<tblUser> _repositoryUser;
        private IRepository<vwTeacherSubjectBinding> _repositoryTeacherSubject;

        public TeacherMasterController()
        {
            this._repositoryTeacher = new Repository<Teacher>();
            this._repositoryUser = new Repository<tblUser>();
            this._repositoryTeacherSubject = new Repository<vwTeacherSubjectBinding>();
        }
        //
        // GET: /Teacher/
        public ActionResult Index()
        {
            List<Teacher> listObj = _repositoryTeacher.GetAll().ToList();
            return View(listObj);
        }

        //
        // GET: /Teacher/Details/5
        public ActionResult Details(int id)
        {
            Teacher objTeacher = _repositoryTeacher.GetById(id);
            return View(objTeacher);
        }

        //
        // GET: /Teacher/Create
        public ActionResult Create()
        {
            TeacherViewModel model = new TeacherViewModel();
            UserMasterModel objUser = new UserMasterModel();
            model.userMasterModel = objUser;
            return View(model);
        }

        //
        // POST: /Teacher/Create
        [HttpPost]
        public ActionResult Create(TeacherViewModel model)
        {
            //ModelState["UserMasterModel.PhoneNo"].Errors.Clear();
            //ModelState["UserMasterModel.State"].Errors.Clear();
            //ModelState["UserMasterModel.City"].Errors.Clear();
            //ModelState["UserMasterModel.Address"].Errors.Clear();
            ModelState.Remove("UserMasterModel.PhoneNo");
            ModelState.Remove("UserMasterModel.State");
            ModelState.Remove("UserMasterModel.City");
            ModelState.Remove("UserMasterModel.Address");
            if (ModelState.IsValid)
            {
                try
                {
                    string[] saAllowedCharacters = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" };

                    tblUser objUser = new tblUser();

                    objUser.FirstName = model.userMasterModel.FirstName;
                    objUser.LastName = model.userMasterModel.LastName;
                    objUser.Email = model.userMasterModel.Email;
                    objUser.LoginPassword = CommonUtility.GenerateRandomOTP(8, saAllowedCharacters);
                    objUser.UserLogo = ""; //model.userMasterModel.UserLogo;
                    objUser.PhoneNo = ""; //model.userMasterModel.PhoneNo;
                    objUser.StateID = 1;//model.userMasterModel.State;
                    objUser.CityID = 1;// model.userMasterModel.City;
                    objUser.CountryID = 1;
                    objUser.Address = ""; //model.userMasterModel.Address;
                    objUser.Created = DateTime.Now;
                    objUser.UserTypeId = 5;
                    objUser.IsActive = true;
                    objUser.IsLoggedIn = false;

                    _repositoryUser.Insert(objUser);

                    Teacher objTeacher = new Teacher();

                    objTeacher.UserId = objUser.ID;
                    objTeacher.QualificationDetail = ""; //model.QualificationDetail;
                    objTeacher.QualificationLevelID = 1; //model.QualificationLevelID;
                    objTeacher.DOB = ""; //model.DOB;
                    objTeacher.ExperienceDetail = model.ExperienceDetail;
                    objTeacher.Created = DateTime.Now;

                    _repositoryTeacher.Insert(objTeacher);


                    //if (model.UserLogoImageFile.FileName != null)
                    //{
                    //    string FileExtension = Path.GetExtension(model.UserLogoImageFile.FileName);
                    //    objUser.UserLogo = Convert.ToString(objUser.ID) + "-" + "UserLogo" + FileExtension;
                    //    string UploadPath = Server.MapPath(SiteSettings.UserLogoImagePath);
                    //    string FilePath = UploadPath + objUser.UserLogo;
                    //    model.UserLogoImageFile.SaveAs(FilePath);

                    //    _repositoryUser.Update(objUser);
                    //}

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }

        //
        // GET: /Teacher/Edit/5
        public ActionResult Edit(int id)
        {
            Teacher objTeacher = _repositoryTeacher.GetById(id);

            UserMasterModel userModel = new UserMasterModel();
            if (objTeacher != null)
            {
                userModel.ID = objTeacher.tblUser.ID;
                userModel.FirstName = objTeacher.tblUser.FirstName;
                userModel.LastName = objTeacher.tblUser.LastName;
                userModel.Email = objTeacher.tblUser.Email;
                userModel.PhoneNo = ""; //objTeacher.tblUser.PhoneNo;
                userModel.Address = ""; //objTeacher.tblUser.Address;
                userModel.City = 1; //objTeacher.tblUser.CityID;
                userModel.State = 1; //objTeacher.tblUser.StateID;
                userModel.UserLogo = "";//objTeacher.tblUser.UserLogo;
            }
            TeacherViewModel model = new TeacherViewModel();

            model.QualificationDetail = ""; //objTeacher.QualificationDetail;
            model.QualificationLevelID = 1; //Convert.ToInt32(objTeacher.QualificationLevelID);
            model.DOB = "";//objTeacher.DOB;
            model.ExperienceDetail = objTeacher.ExperienceDetail;
            model.userMasterModel = userModel;

            return View(model);
        }

        //
        // POST: /Teacher/Edit/5
        [HttpPost]
        public ActionResult Edit(TeacherViewModel model)
        {
            //ModelState["UserMasterModel.PhoneNo"].Errors.Clear();
            //ModelState["UserMasterModel.State"].Errors.Clear();
            //ModelState["UserMasterModel.City"].Errors.Clear();
            //ModelState["UserMasterModel.Address"].Errors.Clear();
            ModelState.Remove("UserMasterModel.PhoneNo");
            ModelState.Remove("UserMasterModel.State");
            ModelState.Remove("UserMasterModel.City");
            ModelState.Remove("UserMasterModel.Address");
            if (ModelState.IsValid)
            {
                try
                {
                    Teacher objEdit = _repositoryTeacher.GetById(model.ID);

                    objEdit.QualificationDetail = "";// model.QualificationDetail;
                    objEdit.QualificationLevelID = 1; //model.QualificationLevelID;
                    objEdit.DOB = ""; //model.DOB;
                    objEdit.ExperienceDetail = model.ExperienceDetail;

                    _repositoryTeacher.Update(objEdit);

                    tblUser objUser = _repositoryUser.GetById(objEdit.UserId);
                    if (objUser != null)
                    {
                        objUser.FirstName = model.userMasterModel.FirstName;
                        objUser.LastName = model.userMasterModel.LastName;
                        objUser.Email = model.userMasterModel.Email;
                        objUser.PhoneNo = "";// model.userMasterModel.PhoneNo;
                        objUser.StateID = 1; //model.userMasterModel.State;
                        objUser.CityID = 1; //model.userMasterModel.City;
                        //objUser.Address = model.userMasterModel.Address;

                        //if (model.UserLogoImageFile != null)
                        //{
                        //    string FileExtension = Path.GetExtension(model.UserLogoImageFile.FileName);
                        //    objUser.UserLogo = Convert.ToString(objUser.ID) + "-" + "UserLogo" + FileExtension;
                        //    string UploadPath = Server.MapPath(SiteSettings.UserLogoImagePath);
                        //    string FilePath = UploadPath + objUser.UserLogo;
                        //    model.UserLogoImageFile.SaveAs(FilePath);
                        //}
                        _repositoryUser.Update(objUser);
                    }
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult TeacherSubject(int id)
        {
            List<vwTeacherSubjectBinding> model = _repositoryTeacherSubject.GetAll().Where(x => x.TeacherId == id).ToList();
            if (model == null)
            {
                model = new List<vwTeacherSubjectBinding>();
            }
            ViewData["Data"] = _repositoryTeacher.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult TeacherSubject(IEnumerable<vwTeacherSubjectBinding> model)
        {
            FinanceEduEntities dbContext = new FinanceEduEntities();
            foreach (vwTeacherSubjectBinding item in model)
            {
                TeacherAndSubject objTAndS = dbContext.TeacherAndSubjects.Where(x => x.SubjectID == item.SubjectId && x.TeacherID == item.TeacherId).FirstOrDefault();
                if (item.Checked == true && objTAndS == null)
                {
                    TeacherAndSubject objNew = new TeacherAndSubject()

FNSWeb/Views/TeacherMaster/Create.cshtml
@model FNSWeb.Models.TeacherViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row row-sm mg-t-20">
    <div class="col-xl-12 mg-t-25 mg-xl-t-0">
        <div class="card pd-20 pd-sm-40 form-layout form-layout-5">
            <h6 class="card-body-title">Teacher Master</h6>
            <p class="mg-b-30">Create Teacher Master with user detail.</p>
            @using (Html.BeginForm("Create", "TeacherMaster", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @*<div class="row row-xs mg-t-20">
                        <div class="col-sm-4 form-control-label">
                            @Html.LabelFor(model => model.QualificationDetail, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.EditorFor(model => model.QualificationDetail, new { @class = "form-control text-box", placeholder = "Enter KioskName" })
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.ValidationMessageFor(model => model.QualificationDetail, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row row-xs mg-t-20">
                        <div class="col-sm-4 form-control-label">
                            @Html.LabelFor(model => model.QualificationLevelID, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.DropDownListFor(model => model.QualificationLevelID, BLL.CommonUtility.GetQualificationLevel(), "Select QualificationLevel", new { @class = "form-control", @required = "required"})
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.ValidationMessageFor(model => model.QualificationLevelID, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.userMasterModel.FirstName, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.userMasterModel.FirstName, new { @class = "text-box" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.userMasterModel.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.userMasterModel.LastName, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.userMasterModel.LastName, new { @class = "text-box" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.userMasterModel.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.userMasterModel.Email, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.userMasterModel.Email, new { @class = "text-box" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.userMasterModel.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.ExperienceDetail, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.ExperienceDetail, new { @class = "text-box" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.ExperienceDetail, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="row row-xs mg-t-20">
                        <div class="col-sm-4 form-control-label">
                            @Html.LabelFor(model => model.DOB, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            <input type="date" id="DOB" name="DOB" class="form-control text-box" />
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row row-xs mg-t-20">
                        <div class="col-sm-4 form-control-label">
                            @Html.LabelFor(model => model.userMasterModel.UserLogo, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            <input type="file" class="btn btn-file" id="UserLogoImageFile" name="UserLogoImageFile" required />
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.ValidationMessageFor(model => model.userMasterModel.UserLogo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row row-xs mg-t-20">
                        <div class="col-sm-4 form-control-label">
                            @Html.LabelFor(model => model.userMasterModel.PhoneNo, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.EditorFor(model => model.userMasterModel.PhoneNo, new { @class = "text-box" })
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.ValidationMessageFor(model => model.userMasterModel.PhoneNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row row-xs mg-t-20">
                        <div class="col-sm-4 form-control-label">
                            @Html.LabelFor(model => model.userMasterModel.State, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.DropDownListFor(model => model.userMasterModel.State, BLL.CommonUtility.GetState(), "Select State", new { @class = "form-control", @required = "required", onchange = "getCityList()" })
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.ValidationMessageFor(model => model.userMasterModel.State, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row row-xs mg-t-20">
                        <div class="col-sm-4 form-control-label">
                            @Html.LabelFor(model => model.userMasterModel.City, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.DropDownListFor(model => model.userMasterModel.City, BLL.CommonUtility.GetCity(1), "Select City", new { @class = "form-control", @required = "required" })
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.ValidationMessageFor(model => model.userMasterModel.City, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row row-xs mg-t-20">
                        <div class="col-sm-4 form-control-label">
                            @Html.LabelFor(model => model.userMasterModel.Address, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.EditorFor(model => model.userMasterModel.Address, new { @class = "text-box" })
                        </div>
                        <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                            @Html.ValidationMessageFor(model => model.userMasterModel.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>
                *@
                <div class="row row-xs mg-t-30">
                    <div class="col-sm-8 mg-l-auto">
                        <div class="form-layout-footer">
                            <button class="btn btn-default mg-r-5">Submit</button>
                            <a href="/TeacherMaster/Index" class="btn btn-secondary">Cancel</a>
                        </div><!-- form-layout-footer -->
                    </div><!-- col-8 -->
                </div>
            }
        </div><!-- card -->
    </div><!-- col-6 -->
</div><!-- row -->
<script type="text/javascript">
    function getCityList() {
        var stateId = $("#userMasterModel_State").val();
        $.ajax
        ({
            url: '/KioskMaster/GetCityList',
            type: 'POST',
            datatype: 'application/json',
            contentType: 'application/json',
            data: JSON.stringify({
                stateId: +stateId
            }),
            success: function (result) {
                $("#userMasterModel_City").html("");
                $("#userMasterModel_City").append($('<option selected></option>').val(0).html('Select City'))
                $.each($.parseJSON(result), function (i, city) {
                    $("#userMasterModel_City").append($('<option></option>').val(city.Value).html(city.Text))
                })
            },
            error: function () {
                alert("Whooaaa! Something went wrong..")
            },
        });
    }

</script>

FNSWeb/Views/TeacherMaster/Details.cshtml
@model DAL.Teacher

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row row-sm mg-t-20">
    <div class="col-xl-12 mg-t-25 mg-xl-t-0">
        <div class="card pd-20 pd-sm-40 form-layout form-layout-5">
            <h6 class="card-body-title">Teacher Master</h6>
            <p class="mg-b-30">Detail of Teacher Master with user detail.</p>
            @*<div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        Qualification Detail
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DisplayFor(model => model.QualificationDetail)
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        Qualification Level
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DisplayFor(model => model.QualificationLevelMaster.Title)
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        DOB
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DisplayFor(model => model.DOB)
                    </div>
                </div>*@


            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    First Name
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.tblUser.FirstName)
                    @*@Model.tblUsers.SingleOrDefault().FirstName*@
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Last Name
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.tblUser.LastName)

                </div>
            </div>
            @*<div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        UserLogo
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        <img src="@Url.Content(Core.SiteSettings.UserLogoImagePath + Model.tblUser.UserLogo)" alt="Sample Image" width="100px" />
                    </div>
                </div>*@
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Email
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.tblUser.Email)

                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    ExperienceDetail
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.ExperienceDetail)
                </div>
            </div>
            @*<div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        Phone No
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">

                        @Html.DisplayFor(model => model.tblUser.PhoneNo)
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        State
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">

                        @Html.DisplayFor(model => model.tblUser.State.Name)
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        City
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">

                        @Html.DisplayFor(model => model.tblUser.City.Name)
                    </div>
                </div>

                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        Address
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">

                        @Html.DisplayFor(model => model.tblUser.Address)
                    </div>
                </div>*@

            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Created
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Model.Created.GetValueOrDefault().ToString("dd/MM/yyyy")
                </div>
            </div>
            <br />
            <div class="row row-xs mg-t-30">
                <div class="col-sm-8 mg-l-auto">
                    <div class="form-layout-footer">
                        <a href="/TeacherMaster/Edit?Id=@Model.ID" class="btn btn-secondary">Edit</a>
                        <a href="/TeacherMaster/Index" class="btn btn-secondary">Back to list</a>
                    </div><!-- form-layout-footer -->
                </div><!-- col-8 -->
            </div>
        </div><!-- card -->
    </div><!-- col-6 -->
</div><!-- row -->

FNSWeb/Views/TeacherMaster/Index.cshtml
@model IEnumerable<DAL.Teacher>

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <div class="card pd-20 pd-sm-40">
        <h6 class="card-body-title">Teacher Master</h6>
        <p class="mg-b-20 mg-sm-b-30">Teacher Master Detail</p>
        <div>
            <a href="Create" class="btn btn-default mg-r-5">Create</a>
            <div class="table-wrapper">
                <table id="datatable1" class="table display responsive nowrap">
                    <thead>
                        <tr>
                            <th class="wd-10p">Name</th>
                            <th class="wd-20p">Email</th>

                            <th class="wd-20p">Experience Detail</th>
                            <th class="wd-20p">Created</th>
                            <th class="wd-10p">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @(item.tblUser.FirstName + " " + item.tblUser.LastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.tblUser.Email)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.ExperienceDetail)
                                </td>
                                <td>@item.Created.GetValueOrDefault().ToString("dd/MM/yyyy")</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.ID })|
                                    @Html.ActionLink("Bind Subject", "TeacherSubject", new { id = item.ID })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div><!-- table-wrapper -->
        </div><!-- card -->