FNSWeb/Models/StudentViewModel.cs
using DAL;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FNSWeb.Models
{
    
    public class StudentViewModel
    {
        public int StudentID { get; set; }
        [Required]
        [Display(Name = "Student Name")]
        public string StudentName { get; set; }
        [Required]
        [Display(Name = "Mother Name")]
        public string MotherName { get; set; }
        [Required]
        [Display(Name = "Father Name")]
        public string FatherName { get; set; }
        [Required]
        [Display(Name = "Mobile No")]
        [Phone]
        public string MobileNo { get; set; }
        [Required]
        [Display(Name = "Date of Birth")]
        public string DOB { get; set; }
        [Display(Name = "Mailing Address")]
        public string MailingAddress { get; set; }
        [Display(Name = "Permanent Address")]
        public string PermanentAddress { get; set; }
        [Display(Name = "Address Proof")]
        public Nullable<int> AddressProofID { get; set; }
        [Display(Name = "Address ProofT ext")]
        public string AddressProofText { get; set; }
        public string CreatedBy { get; set; }
        
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
        //[Required]
        //[DataType(DataType.Password)]
        //[Display(Name = "Password")]
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string StudentPic { get; set; }
        public HttpPostedFileBase StudentPicImageFile { get; set; }
        public Nullable<int> Gender { get; set; }
    }

    

}

FNSWeb/Controllers/StudentController.cs
using BLL;
using Core;
using DAL;
using FNSWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FNSWeb.Controllers
{
    [SessionAuthorize]
    public class StudentController : Controller
    {
        //
        // GET: /Student/
        private IRepository<tblStudent> _repository;

        public StudentController()
        {
            this._repository = new Repository<tblStudent>();
        }

        public ActionResult Index()
        {
            List<tblStudent> obj = _repository.GetAll().ToList();
            if (obj != null && Session["UserMaster"] != null)
            {
                if (((UserMaster)Session["UserMaster"]).UserTypeId == 2)
                {
                    int CreatedBy = ((UserMaster)Session["UserMaster"]).ID;
                    obj = obj.Where(x => x.CreatedBy == CreatedBy).ToList();
                }
            }

            return View(obj);
        }

        //
        // GET: /Student/Details/5
        public ActionResult Details(int id)
        {
            tblStudent objStudent = _repository.GetById(id);
            return View(objStudent);
        }

        //
        // GET: /Student/Create
        public ActionResult Create()
        {
            StudentViewModel model = new StudentViewModel();
            return View(model);
        }

        //
        // POST: /Student/Create
        [HttpPost]
        public ActionResult Create(StudentViewModel objStudent)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string[] saAllowedCharacters = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" };

                    int CreatedBy = (Session["UserMaster"] != null ? ((UserMaster)Session["UserMaster"]).ID : 1);

                    tblStudent objStudentModel = new tblStudent();
                    objStudentModel.StudentName = objStudent.StudentName;
                    objStudentModel.MotherName = objStudent.MotherName;
                    objStudentModel.FatherName = objStudent.FatherName;
                    objStudentModel.MobileNo = objStudent.MobileNo;
                    objStudentModel.DOB = objStudent.DOB;
                    objStudentModel.MailingAddress = objStudent.MailingAddress;
                    objStudentModel.PermanentAddress = objStudent.PermanentAddress;
                    objStudentModel.AddressProofID = objStudent.AddressProofID;
                    objStudentModel.AddressProofText = objStudent.AddressProofText;
                    objStudentModel.CreatedBy = CreatedBy;
                    objStudentModel.UserName = Guid.NewGuid().ToString().Replace("-", "").Substring(12); //objStudent.UserName;
                    objStudentModel.Email = objStudent.Email;
                    objStudentModel.Password = CommonUtility.GenerateRandomOTP(8, saAllowedCharacters);
                    objStudentModel.IsActive = true;
                    objStudentModel.CityID = objStudent.CityID;
                    objStudentModel.StateID = objStudent.StateID;
                    objStudentModel.Created = DateTime.Now;
                    objStudentModel.StudentPic = objStudent.StudentPic;
                    objStudentModel.Gender = objStudent.Gender;

                    _repository.Insert(objStudentModel);
                    if (objStudent.StudentPicImageFile != null)
                    {
                        string FileExtension = Path.GetExtension(objStudent.StudentPicImageFile.FileName);
                        objStudentModel.StudentPic = Convert.ToString(objStudentModel.StudentID) + "-" + "StudentPic" + FileExtension;
                        string UploadPath = Server.MapPath(SiteSettings.StudentPicImagePath);
                        string FilePath = UploadPath + objStudentModel.StudentPic;
                        objStudent.StudentPicImageFile.SaveAs(FilePath);

                        _repository.Update(objStudentModel);
                    }

                    return RedirectToAction("Index");
                }
                return View(objStudent);
            }
            catch
            {
                return View(objStudent);
            }
        }

        public ActionResult GetStudentBatchDetail(int id)
        {
            StudentBatchViewModel model = new StudentBatchViewModel();
            return View(model);
        }
        //
        // GET: /Student/Edit/5
        public ActionResult Edit(int id)
        {
            tblStudent objStudent = _repository.GetById(id);
            StudentViewModel objStudentModel = new StudentViewModel();
            objStudentModel.StudentID = objStudent.StudentID;
            objStudentModel.StudentName = objStudent.StudentName;
            objStudentModel.MotherName = objStudent.MotherName;
            objStudentModel.FatherName = objStudent.FatherName;
            objStudentModel.MobileNo = objStudent.MobileNo;
            objStudentModel.DOB = objStudent.DOB;
            objStudentModel.MailingAddress = objStudent.MailingAddress;
            objStudentModel.PermanentAddress = objStudent.PermanentAddress;
            objStudentModel.AddressProofID = objStudent.AddressProofID;
            objStudentModel.AddressProofText = objStudent.AddressProofText;
            //objStudentModel.CreatedBy = Convert.ToString(objStudent.CreatedBy);
            //objStudentModel.UserName = objStudent.UserName;
            objStudentModel.Email = objStudent.Email;
            objStudentModel.Password = objStudent.Password;
            objStudentModel.IsActive = true;
            objStudentModel.CityID = objStudent.CityID;
            objStudentModel.StateID = objStudent.StateID;
            objStudentModel.Created = DateTime.Now;
            objStudentModel.StudentPic = objStudent.StudentPic;
            objStudentModel.Gender = objStudent.Gender;

            return View(objStudentModel);
        }

        //
        // POST: /Student/Edit/5
        [HttpPost]
        public ActionResult Edit(StudentViewModel objStudent)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tblStudent objStudentModel = _repository.GetById(objStudent.StudentID);
                    objStudentModel.StudentName = objStudent.StudentName;
                    objStudentModel.MotherName = objStudent.MotherName;
                    objStudentModel.FatherName = objStudent.FatherName;
                    objStudentModel.MobileNo = objStudent.MobileNo;
                    objStudentModel.DOB = objStudent.DOB;
                    objStudentModel.MailingAddress = objStudent.MailingAddress;
                    objStudentModel.PermanentAddress = objStudent.PermanentAddress;
                    objStudentModel.AddressProofID = objStudent.AddressProofID;
                    objStudentModel.AddressProofText = objStudent.AddressProofText;
                    //objStudentModel.CreatedBy = Convert.ToInt32(1);
                    //objStudentModel.UserName = objStudent.UserName;
                    objStudentModel.Email = objStudent.Email;
                    objStudentModel.CityID = objStudent.CityID;
                    objStudentModel.StateID = objStudent.StateID;
                    objStudentModel.Gender = objStudent.Gender;
                    if (objStudent.StudentPicImageFile != null)
                    {
                        string FileExtension = Path.GetExtension(objStudent.StudentPicImageFile.FileName);
                        objStudentModel.StudentPic = Convert.ToString(objStudentModel.StudentID) + "-" + "StudentPic" + FileExtension;
                        string UploadPath = Server.MapPath(SiteSettings.StudentPicImagePath);
                        string FilePath = UploadPath + objStudentModel.StudentPic;
                        objStudent.StudentPicImageFile.SaveAs(FilePath);
                    }
                    _repository.Update(objStudentModel);

                    return RedirectToAction("Index");
                }
                return View(objStudent);
            }
            catch
            {
                return View(objStudent);
            }
        }

        //
        // GET: /Student/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Student/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

FNSWeb/Views/Student/Create.cshtml
@model FNSWeb.Models.StudentViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row row-sm mg-t-20">
    <div class="col-xl-12 mg-t-25 mg-xl-t-0">
        <div class="card pd-20 pd-sm-40 form-layout form-layout-5">
            <h6 class="card-body-title">Student Master</h6>
            <p class="mg-b-30">Create Student Master.</p>
            @using (Html.BeginForm("Create", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.StudentName, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.StudentName, new { @class = "form-control text-box", placeholder = "Enter StudentName" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.MotherName, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.MotherName, new { @class = "form-control text-box", placeholder = "Enter MotherName" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.MotherName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.FatherName, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.FatherName, new { @class = "form-control text-box", placeholder = "Enter FatherName" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.MobileNo, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.MobileNo, new { @class = "form-control text-box", placeholder = "Enter MobileNo" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.DOB, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @*@Html.EditorFor(model => model.DOB, new { @class = "form-control text-box", placeholder = "Enter DOB", @type="date" })*@
                        <input type="date" id="DOB" name="DOB" class="form-control text-box" />
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.MailingAddress, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.MailingAddress, new { @class = "form-control text-box", placeholder = "Enter Mailing Address" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.MailingAddress, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.PermanentAddress, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.PermanentAddress, new { @class = "form-control text-box", placeholder = "Enter Permanent Address" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.PermanentAddress, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.AddressProofID, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        <input type="hidden" id="ddlStateVal" value="" />
                        @Html.DropDownListFor(model => model.AddressProofID, BLL.CommonUtility.GetAddressProof(), "Select Address proof", new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.AddressProofID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.AddressProofText, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.AddressProofText, new { @class = "form-control text-box", placeholder = "Enter StudentName" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.AddressProofText, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.UserName, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.UserName, new { @class = "form-control text-box", placeholder = "Enter UserName" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.Email, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.Email, new { @class = "form-control text-box", placeholder = "Enter Email" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.StateID, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        <input type="hidden" id="ddlStateVal" value="" />
                        @Html.DropDownListFor(model => model.StateID, BLL.CommonUtility.GetState(), "Select State", new { @class = "form-control", @required = "required", onchange = "getCityList()" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.StateID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.CityID, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DropDownListFor(model => model.CityID, BLL.CommonUtility.GetCity(1), "Select City", new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.Gender, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @*@Html.EditorFor(model => model.Gender, new { @class = "form-control text-box", placeholder = "Enter Gender" })*@
                        @Html.DropDownListFor(model => model.Gender, BLL.CommonUtility.GetGender(), "Select Gender", new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.StudentPic, new { @class = "form-control-label" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        <input type="file" class="btn btn-file" id="StudentPicImageFile" name="StudentPicImageFile"/>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.StudentPic, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-30">
                    <div class="col-sm-8 mg-l-auto">
                        <div class="form-layout-footer">
                            <button class="btn btn-default mg-r-5">Submit</button>
                            <a href="/Student/Index" class="btn btn-secondary">Cancel</a>
                        </div><!-- form-layout-footer -->
                    </div><!-- col-8 -->
                </div>
            }
        </div><!-- card -->
    </div><!-- col-6 -->
</div><!-- row -->
<script type="text/javascript">
    function getCityList() {
        var stateId = $("#UserDetail_State").val();
        $.ajax
        ({
            url: '/KioskMaster/GetCityList',
            type: 'POST',
            datatype: 'application/json',
            contentType: 'application/json',
            data: JSON.stringify({
                stateId: +stateId
            }),
            success: function (result) {
                $("#UserDetail_City").html("");
                $("#UserDetail_City").append($('<option selected></option>').val(0).html('Select City'))
                $.each($.parseJSON(result), function (i, city) {
                    $("#UserDetail_City").append($('<option></option>').val(city.Value).html(city.Text))
                })
            },
            error: function () {
                alert("Whooaaa! Something went wrong..")
            },
        });
    }

</script>

FNSWeb/Views/Student/GetStudentBatchDetail.cshtml
@*@model FNSWeb.Models.StudentBatchViewModel
@{
    ViewBag.Title = "Student Batch Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@



FNSWeb/Views/Student/Index.cshtml
@model IEnumerable<DAL.tblStudent>

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <div class="card pd-20 pd-sm-40">
        <h6 class="card-body-title">Student</h6>
        <p class="mg-b-20 mg-sm-b-30">Student Detail</p>
        <div>
            <a href="Create" class="btn btn-default mg-r-5">Create</a>
            <div class="table-wrapper">
                <table id="datatable1" class="table display responsive nowrap">
                    <thead>
                        <tr>
                            <th class="wd-10p">
                                Student Name
                            </th>
                            <th class="wd-10p">
                                Mother Name
                            </th>
                            <th class="wd-10p">
                                Father Name
                            </th>
                            <th class="wd-10p">
                               UserName
                            </th>
                            <th class="wd-10p">
                                Mobile No
                            </th>
                            <th class="wd-10p">
                                Date of Birth
                            </th>
                            <th class="wd-10p">
                                Email
                            </th>
                            <th class="wd-10p">
                                Gender
                            </th>
                            <th class="wd-10p">
                                StudentPic
                            </th>
                            <th class="wd-10p">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StudentName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MotherName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FatherName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MobileNo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DOB)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @if (item.Gender == 1)
                                    {
                                       <label>Male</label>  
                                    }
                                    else
                                    {
                                         <label>Female</label>  
                                    }
                                </td>
                                <td>
                                    @if (item.StudentPic != "" && item.StudentPic != null)
                                    {
                                        <img src="@Url.Content(Core.SiteSettings.StudentPicImagePath + item.StudentPic)" alt="@item.StudentPic" width="50px" />
                                    }
                                    else
                                    {
                                        <label></label>
                                    }
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.StudentID }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.StudentID })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div><!-- table-wrapper -->
        </div><!-- card -->
    </div>