FNSWeb/Models/SubjectViewModel.cs
using DAL;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FNSWeb.Models
{
    public class SubjectViewModel
    {

        public int ID { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Is Active")]
        public bool IsActive { get; set; }
        public DateTime Created { get; set; }

        public List<CourseViewModel> lstCourseViewModel { get; set; }
        public List<TopicViewModel> lstTopicViewModel { get; set; }
        public List<TeacherViewModel> lstTeacherViewModel { get; set; } 
    }
}

FNSWeb/Controllers/SubjectController.cs
using BLL;
using Core;
using DAL;
using FNSWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FNSWeb.Controllers
{
    [SessionAuthorize]
    public class SubjectController : Controller
    {
        private IRepository<Subject> _repositorySubject;
        public SubjectController()
        {
            this._repositorySubject = new Repository<Subject>();
        }
        //
        // GET: /Subject/
        public ActionResult Index()
        {
            List<Subject> listObj = _repositorySubject.GetAll().ToList();
            return View(listObj);
        }

        //
        // GET: /Subject/Details/5
        public ActionResult Details(int id)
        {
            SubjectViewModel model = new SubjectViewModel();
            Subject objSubject = _repositorySubject.GetById(id);
            model.ID = objSubject.ID;
            model.Name = objSubject.Name;
            model.Description = objSubject.Description;
            model.IsActive = Convert.ToBoolean(objSubject.IsActive);
            model.Created = Convert.ToDateTime(objSubject.Created);

            return View(model);
        }

        //
        // GET: /Subject/Create
        public ActionResult Create()
        {
            SubjectViewModel model = new SubjectViewModel();
            return View(model);
        }

        //
        // POST: /Subject/Create
        [HttpPost]
        public ActionResult Create(SubjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Subject objSubject = new Subject();

                    objSubject.Name = model.Name;
                    objSubject.Description = model.Description;
                    objSubject.IsActive = model.IsActive;
                    objSubject.Created = DateTime.Now;

                    _repositorySubject.Insert(objSubject);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }

        //
        // GET: /Subject/Edit/5
        public ActionResult Edit(int id)
        {
            Subject objSubject = _repositorySubject.GetById(id);

            SubjectViewModel model = new SubjectViewModel();
            model.ID = objSubject.ID;
            model.Name = objSubject.Name;
            model.Description = objSubject.Description;
            model.IsActive = Convert.ToBoolean(objSubject.IsActive);
            model.Created = Convert.ToDateTime(objSubject.Created);

            return View(model);
        }

        //
        // POST: /Subject/Edit/5
        [HttpPost]
        public ActionResult Edit(SubjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Subject objEdit = _repositorySubject.GetById(model.ID);

                    objEdit.Name = model.Name;
                    objEdit.Description = model.Description;
                    objEdit.IsActive = model.IsActive;

                    _repositorySubject.Update(objEdit);

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

FNSWeb/Views/Subject/Create.cshtml
@model FNSWeb.Models.SubjectViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row row-sm mg-t-20">
    <div class="col-xl-12 mg-t-25 mg-xl-t-0">
        <div class="card pd-20 pd-sm-40 form-layout form-layout-5">
            <h6 class="card-body-title">Subject Master</h6>
            <p class="mg-b-30">Create Subject Master.</p>
            @using (Html.BeginForm("Create", "Subject", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.Name, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.Name, new { @class = "form-control text-box", placeholder = "Enter Subject Name" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.Description, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.Description, new { @class = "text-box" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.IsActive, new { @class = "form-control-label" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.IsActive, new { @class = "text-box" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">

                    </div>
                </div>

                <div class="row row-xs mg-t-30">
                    <div class="col-sm-8 mg-l-auto">
                        <div class="form-layout-footer">
                            <button class="btn btn-default mg-r-5">Submit </button>
                            <a href="/Subject/Index" class="btn btn-secondary">Cancel</a>
                        </div><!-- form-layout-footer -->
                    </div><!-- col-8 -->
                </div>
            }
        </div><!-- card -->
    </div><!-- col-6 -->
</div><!-- row -->

FNSWeb/Views/Subject/Details.cshtml
@model FNSWeb.Models.SubjectViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row row-sm mg-t-20">
    <div class="col-xl-12 mg-t-25 mg-xl-t-0">
        <div class="card pd-20 pd-sm-40 form-layout form-layout-5">
            <h6 class="card-body-title">Subject Master</h6>
            <p class="mg-b-30">Detail of Subject Master.</p>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    @Html.DisplayNameFor(model => model.Name)
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.Name)
                </div>
            </div>

            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    @Html.DisplayNameFor(model => model.Description)
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    @Html.DisplayNameFor(model => model.IsActive)
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.IsActive)
                </div>
            </div>


            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Created On
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Model.Created.ToString("dd/MM/yyyy")
                </div>
            </div>
            <br />
            <div class="row row-xs mg-t-30">
                <div class="col-sm-8 mg-l-auto">
                    <div class="form-layout-footer">
                        <a href="/Subject/Edit?Id=@Model.ID" class="btn btn-secondary">Edit</a>
                        <a href="/Subject/Index" class="btn btn-secondary">Back to list</a>
                    </div><!-- form-layout-footer -->
                </div><!-- col-8 -->
            </div>
        </div><!-- card -->
    </div><!-- col-6 -->
</div><!-- row -->

FNSWeb/Views/Subject/Edit.cshtml
@model FNSWeb.Models.SubjectViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row row-sm mg-t-20">
    <div class="col-xl-12 mg-t-25 mg-xl-t-0">
        <div class="card pd-20 pd-sm-40 form-layout form-layout-5">
            <h6 class="card-body-title">Subject Master</h6>
            <p class="mg-b-30">Edit Subject Master.</p>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.ID)
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.Name, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.Name, new { @class = "form-control text-box", placeholder = "Enter Subject Name" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.Description, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.Description, new { @class = "text-box" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.IsActive, new { @class = "form-control-label" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.IsActive, new { @class = "text-box" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">

                    </div>
                </div>

                <div class="row row-xs mg-t-30">
                    <div class="col-sm-8 mg-l-auto">
                        <div class="form-layout-footer">
                            <button class="btn btn-default mg-r-5">Submit</button>
                            <a href="/Subject/Index" class="btn btn-secondary">Cancel</a>
                        </div><!-- form-layout-footer -->
                    </div><!-- col-8 -->
                </div>
            }
        </div><!-- card -->
    </div><!-- col-6 -->
</div><!-- row -->

FNSWeb/Views/Subject/Index.cshtml
@model IEnumerable<DAL.Subject>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card pd-20 pd-sm-40">
    <h6 class="card-body-title">Subject Master</h6>
    <p class="mg-b-20 mg-sm-b-30">Subject Master Details</p>
    <div>
        <a href="Create" class="btn btn-default mg-r-5">Create</a>
        <div class="table-wrapper">
            <table id="datatable1" class="table display responsive nowrap">
                <thead>
                    <tr>
                        <th class="wd-20p">@Html.DisplayNameFor(model => model.Name)</th>
                        <th class="wd-20p">@Html.DisplayNameFor(model => model.Description)</th>
                        <th class="wd-20p">Active</th>
                        <th class="wd-20p">@Html.DisplayNameFor(model => model.Created)</th>
                        <th class="wd-20p">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>
                            <td>@item.Created.GetValueOrDefault().ToString("dd/MM/yyyy")</td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.ID })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div><!-- table-wrapper -->
    </div>
</div><!-- card -->