FNSWeb/Models/ContentMasterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FNSWeb.Models
{
    public class ContentMasterViewModel
    {
        public int ID { get; set; }
        [Required]
        [Display(Name = "Course")]
        public int CourseID { get; set; }
        [Required]
        [Display(Name = "Subject")]
        public int SubjectID { get; set; }
        [Required]
        [Display(Name = "Topic")]
        public int TopicID { get; set; }
        [Required]
        [Display(Name = "Teacher")]
        public int TeacherId { get; set; }
        [Display(Name = "Content Type Master")]
        public int ContentTypeMasterID { get; set; }

        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; }

        public string FileName { get; set; }

        [Display(Name = "File Sequence No")]
        public int SequenceNo { get; set; }

        public Nullable<bool> IsActive { get; set; }
        public DateTime Created { get; set; }
        public HttpPostedFileBase[] ContentDocument { get; set; }
        public TeacherViewModel teacherViewModel { get; set; }
        public CourseViewModel courseViewModel { get; set; }
        public SubjectViewModel subjectViewModel { get; set; }
        public TopicViewModel topicViewModel { get; set; }
        public ContentTypeviewmodel contentTypeviewmodel { get; set; }
    }
}

FNSWeb/Controllers/ContentMasterController.cs
using BLL;
using Core;
using DAL;
using FNSWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FNSWeb.Controllers
{
    [SessionAuthorize]
    public class ContentMasterController : Controller
    {
        private IRepository<ContentMaster> _repositoryContent;
        

        public ContentMasterController()
        {
            this._repositoryContent = new Repository<ContentMaster>();
            
        }
        //
        // GET: /ContentMaster/
        public ActionResult Index()
        {
            List<ContentMaster> listObj = _repositoryContent.GetAll().ToList();
            return View(listObj);
        }

        //
        // GET: /ContentMaster/Details/5
        public ActionResult Details(int id)
        {
            ContentMaster objContent = _repositoryContent.GetById(id);
            return View(objContent);
        }

        //
        // GET: /ContentMaster/Create
        public ActionResult Create()
        {
            ContentMasterViewModel model = new ContentMasterViewModel();
            return View(model);
        }

        //
        // POST: /ContentMaster/Create
        [HttpPost]
        public ActionResult Create(ContentMasterViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ContentMaster objContentMaster = new ContentMaster();

                    objContentMaster.CourseID = model.CourseID;
                    objContentMaster.SubjectID = model.SubjectID;
                    objContentMaster.TopicID = model.TopicID;
                    objContentMaster.TeacherId = model.TeacherId;
                    //objContentMaster.ContentTypeMasterID = model.ContentTypeMasterID;
                    objContentMaster.Title = model.Title;
                    objContentMaster.Description = model.Description;
                    //objContentMaster.SequenceNo = model.SequenceNo;
                    objContentMaster.IsActive = true;
                    objContentMaster.Created = DateTime.Now;

                    _repositoryContent.Insert(objContentMaster);
                    string filesName = string.Empty;
                    foreach (HttpPostedFileBase file in model.ContentDocument)
                    {
                        //string FileExtension = Path.GetExtension(file.FileName);
                        string prefix = Guid.NewGuid().ToString().Replace("-", "").Substring(0, 8);

                        objContentMaster.FileName = Convert.ToString(objContentMaster.ID) + "_" + prefix + file.FileName;
                        string UploadPath = Server.MapPath(SiteSettings.ContentFilePath);
                        string FilePath = UploadPath + objContentMaster.FileName;
                        filesName += objContentMaster.FileName + "|";
                        file.SaveAs(FilePath);
                    }
                    objContentMaster.FileName = filesName; 
                    _repositoryContent.Update(objContentMaster);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw ex;
                    //return View(model);
                }
            }
            return View(model);
        }

        //
        // GET: /ContentMaster/Edit/5
        public ActionResult Edit(int id)
        {
            ContentMaster model = _repositoryContent.GetById(id);

            ContentMasterViewModel objContentMaster = new ContentMasterViewModel();
            objContentMaster.ID = model.ID;
            objContentMaster.CourseID = Convert.ToInt32(model.CourseID);
            objContentMaster.SubjectID = Convert.ToInt32(model.SubjectID);
            objContentMaster.TopicID = Convert.ToInt32(model.TopicID);
            objContentMaster.TeacherId = Convert.ToInt32(model.TeacherId);
            //objContentMaster.ContentTypeMasterID = Convert.ToInt32(model.ContentTypeMasterID);
            objContentMaster.Title = model.Title;
            objContentMaster.Description = model.Description;
            //objContentMaster.SequenceNo = Convert.ToInt32(model.SequenceNo);
            objContentMaster.FileName = model.FileName;
            objContentMaster.IsActive = model.IsActive;
            

            return View(objContentMaster);
        }

        //
        // POST: /ContentMaster/Edit/5
        [HttpPost]
        public ActionResult Edit(ContentMasterViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ContentMaster objEdit = _repositoryContent.GetById(model.ID);

                    objEdit.CourseID = model.CourseID;
                    objEdit.SubjectID = model.SubjectID;
                    objEdit.TopicID = model.TopicID;
                    objEdit.TeacherId = model.TeacherId;
                    //objEdit.ContentTypeMasterID = model.ContentTypeMasterID;
                    objEdit.Title = model.Title;
                    objEdit.Description = model.Description;
                    //objEdit.SequenceNo = model.SequenceNo;

                    if (model.ContentDocument[0] != null)
                    {
                        string filesName = string.Empty;
                        foreach (HttpPostedFileBase file in model.ContentDocument)
                        {
                            string prefix = Guid.NewGuid().ToString().Replace("-", "").Substring(0, 8);
                            //string FileExtension = Path.GetExtension(file.FileName);
                            model.FileName = Convert.ToString(model.ID) + "_" + prefix + file.FileName;
                            string UploadPath = Server.MapPath(SiteSettings.ContentFilePath);
                            string FilePath = UploadPath + model.FileName;
                            filesName += model.FileName + "|";
                            file.SaveAs(FilePath);
                        }
                        objEdit.FileName += filesName;
                    }
                    _repositoryContent.Update(objEdit);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw ex;
                    //return View(model);
                }
            }
            return View(model);
        }
       
        public ActionResult DeleteFile(int id, string FileName, string Type)
        {
            ContentMaster model = _repositoryContent.GetById(id);
            model.FileName = model.FileName.Replace(FileName + "|", "");
            if (Type == "1")
            {
                if (System.IO.File.Exists(Server.MapPath(SiteSettings.ContentFilePath + FileName)))
                {
                    System.IO.File.Delete(Server.MapPath(SiteSettings.ContentFilePath + FileName));
                }
                _repositoryContent.Update(model);
            }
            else if (Type == "2")
            {
                string FileExtension = Path.GetExtension(FileName);
                string FilePath = Server.MapPath(SiteSettings.ContentFilePath + FileName);
                //if (FileExtension.ToLower() == ".pdf" || FileExtension.ToLower() == ".jpg" || FileExtension.ToLower() == ".txt")
                //{
                //    //GetReport(FilePath);
                //}
                //else
                //{
                    System.IO.FileInfo file = new System.IO.FileInfo(FilePath);
                    if (file.Exists)
                    {
                        Response.Clear();
                        Response.AddHeader("Content-Disposition", "attachment; filename=" + file.Name);
                        Response.AddHeader("Content-Length", file.Length.ToString());
                        Response.ContentType = "application/octet-stream";
                        Response.WriteFile(file.FullName);
                        Response.End();
                    }
                //}
            }
            return Redirect("/ContentMaster/Edit?id=" + id);
        }

        public FileResult GetReport(string file)
        {
            string FilePath = Server.MapPath(SiteSettings.ContentFilePath + file);
            byte[] FileBytes = System.IO.File.ReadAllBytes(FilePath);
            string FileExtension = Path.GetExtension(file);
            return File(FileBytes, "application/pdf");
        }    
    }
}

FNSWeb/Views/ContentMaster/Create.cshtml
@model FNSWeb.Models.ContentMasterViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row row-sm mg-t-20">
    <div class="col-xl-12 mg-t-25 mg-xl-t-0">
        <div class="card pd-20 pd-sm-40 form-layout form-layout-5">
            <h6 class="card-body-title">Content Master</h6>
            <p class="mg-b-30">Create Content Master .</p>
            @using (Html.BeginForm("Create", "ContentMaster", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.CourseID, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DropDownListFor(model => model.CourseID, BLL.CommonUtility.GetCourse(), "Select Course", new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.SubjectID, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DropDownListFor(model => model.SubjectID, BLL.CommonUtility.GetSubject(), "Select Subject", new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.TopicID, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DropDownListFor(model => model.TopicID, BLL.CommonUtility.GetTopic(), "Select Topic", new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.TopicID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.Title, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.Title, new { @class = "form-control text-box", placeholder = "Enter Title" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.Description, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.Description, new { @class = "form-control text-box", placeholder = "Enter Description", rows = "20" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.FileName, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        <input type="file" class="btn btn-file" id="ContentDocument" name="ContentDocument" multiple required />
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.ContentTypeMasterID, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DropDownListFor(model => model.ContentTypeMasterID, BLL.CommonUtility.GetContentType(), "Select Content Type", new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.ContentTypeMasterID, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                @*<div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.SequenceNo, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.EditorFor(model => model.SequenceNo, new { @class = "form-control text-box", placeholder = "Enter SequenceNo" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.SequenceNo, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                <div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        @Html.LabelFor(model => model.TeacherId, new { @class = "form-control-label" })<span class="tx-danger">*</span>
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DropDownListFor(model => model.TeacherId, BLL.CommonUtility.GetTeacher(), "Select Teacher", new { @class = "form-control", @required = "required" })
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row row-xs mg-t-30">
                    <div class="col-sm-8 mg-l-auto">
                        <div class="form-layout-footer">
                            <button class="btn btn-default mg-r-5">Submit</button>
                            <a href="/ContentMaster/Index" class="btn btn-secondary">Cancel</a>
                        </div><!-- form-layout-footer -->
                    </div><!-- col-8 -->
                </div>
            }
        </div><!-- card -->
    </div><!-- col-6 -->
</div><!-- row -->

FNSWeb/Views/ContentMaster/Details.cshtml
@model DAL.ContentMaster

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row row-sm mg-t-20">
    <div class="col-xl-12 mg-t-25 mg-xl-t-0">
        <div class="card pd-20 pd-sm-40 form-layout form-layout-5">
            <h6 class="card-body-title">Content Master</h6>
            <p class="mg-b-30">Detail of Content Master.</p>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Course
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.Course.CourseName)
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Subject
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.Subject.Name)
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Topic
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.Topic.Name)
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Title
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.Title)
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Description
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    View Files
                </div>
                <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                    @if (Model.FileName != null && Model.FileName != "")
                    {
                        string[] files = Model.FileName.Split('|');
                        foreach (string file in files)
                        {
                            if (file != "")
                            {
                                string FileName = file.Replace(Convert.ToString(Model.ID) + "_", "");
                                FileName = FileName.Substring(8);
                                string FileExtension = Path.GetExtension(FileName);
                                if (FileExtension.ToLower() == ".pdf")
                                {
                                    <div style="float: left; padding: 0px 8px 0px 8px;">
                                        <div style="margin-left:25px;">
                                            <i class="fa fa-file-pdf-o" style="font-size:48px;color:red" title="@FileName"></i>
                                        </div>
                                        <div style="align-content:center;">
                                            <a href="/ContentMaster/DeleteFile?id=@Model.ID&FileName=@file&Type=1">Delete</a> |
                                            <a href="#" onclick="GetClientReport('@file')">View</a>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div style="float: left; padding: 0px 8px 0px 8px;">
                                        @if (FileExtension.ToLower() == ".doc" || FileExtension.ToLower() == ".docx")
                                        {
                                            <div style="margin-left:35px;">
                                                <i class="fa fa-file-word-o" style="font-size:48px;color:red" title="@FileName"></i>
                                            </div>
                                        }
                                        @if (FileExtension.ToLower() == ".txt")
                                        {
                                            <div style="margin-left:35px;">
                                                <i class="fa fa-file-text" style="font-size:48px;color:red" title="@FileName"></i>
                                            </div>
                                        }
                                        @if (FileExtension.ToLower() == ".mp4")
                                        {
                                            <div style="margin-left:35px;">
                                                <i class="fa fa-file-video-o" style="font-size:48px;color:red" title="@FileName"></i>
                                            </div>
                                        }
                                        @if (FileExtension.ToLower() == ".png" || FileExtension.ToLower() == ".jpg")
                                        {
                                            <div style="margin-left:35px;">
                                                <i class="fa fa-file-image-o" style="font-size:48px;color:red" title="@FileName"></i>
                                            </div>
                                        }
                                        @if (FileExtension.ToLower() == ".xls" || FileExtension.ToLower() == ".xlsx")
                                        {
                                            <div style="margin-left:35px;">
                                                <i class="fa fa-file-excel-o" style="font-size:48px;color:red" title="@FileName"></i>
                                            </div>
                                        }
                                        @if (FileExtension.ToLower() == ".pptx")
                                        {
                                            <div style="margin-left:35px;">
                                                <i class="fa fa-file-powerpoint-o" style="font-size:48px;color:red" title="@FileName"></i>
                                            </div>
                                        }
                                        <div style="align-content:center;">
                                            <a href="/ContentMaster/DeleteFile?id=@Model.ID&FileName=@file&Type=1">Delete</a> |
                                            <a href="/ContentMaster/DeleteFile?id=@Model.ID&FileName=@file&Type=2">Download</a>
                                        </div>
                                    </div>
                                }
                            }
                        }
                    }
                </div>
            </div>
            @*<div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        Content Type
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DisplayFor(model => model.ContentTypeMaster.Title)
                    </div>
                </div>*@
            @*<div class="row row-xs mg-t-20">
                    <div class="col-sm-4 form-control-label">
                        Sequence No
                    </div>
                    <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                        @Html.DisplayFor(model => model.SequenceNo)
                    </div>
                </div>*@
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    IsActive
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.IsActive)
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Created
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Model.Created.GetValueOrDefault().ToString("dd/MM/yyyy")
                </div>
            </div>
            <div class="row row-xs mg-t-20">
                <div class="col-sm-4 form-control-label">
                    Teacher
                </div>
                <div class="col-sm-4 mg-t-10 mg-sm-t-0">
                    @Html.DisplayFor(model => model.Teacher.tblUser.FirstName) @Html.DisplayFor(model => model.Teacher.tblUser.LastName)
                </div>
            </div>
            <br />
            <div class="row row-xs mg-t-30">
                <div class="col-sm-8 mg-l-auto">
                    <div class="form-layout-footer">
                        <a href="/ContentMaster/Edit?Id=@Model.ID" class="btn btn-secondary">Edit</a>
                        <a href="/ContentMaster/Index" class="btn btn-secondary">Back to list</a>
                    </div><!-- form-layout-footer -->
                </div><!-- col-8 -->
            </div>
        </div><!-- card -->
    </div><!-- col-6 -->
</div><!-- row -->
<script>
    function GetClientReport(fileName) {
        window.open("/ContentMaster/GetReport?file=" + fileName, "_blank");
    };
</script>

FNSWeb/Views/ContentMaster/Index.cshtml
@model IEnumerable<DAL.ContentMaster>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card pd-20 pd-sm-40">
    <h6 class="card-body-title">Content Master</h6>
    <p class="mg-b-20 mg-sm-b-30">Content Master Detail</p>
    <div>
        <a href="Create" class="btn btn-default mg-r-5">Create</a>
        <div class="table-wrapper">
            <table id="datatable1" class="table display responsive nowrap">
                <thead>
                    <tr>
                        <th class="wd-10p">
                            Course
                        </th>
                        <th class="wd-10p">
                            Subject
                        </th>
                        <th class="wd-10p">
                            Topic
                        </th>
                        <th class="wd-10p">
                            Teacher
                        </th>
                        <th class="wd-20p">
                            Title
                        </th>
                        @*<th class="wd-10p">
                            Content Type
                        </th>*@
                        @*<th class="wd-10p">
                            Sequence No
                        </th>*@
                        <th class="wd-10p">
                            IsActive
                        </th>
                        <th class="wd-10p">
                            Created
                        </th>
                        <th class="wd-20p">
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Course.CourseName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Subject.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Topic.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TeacherId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.ContentTypeMaster.Title)
                            </td>*@
                            @*<td>
                                @Html.DisplayFor(modelItem => item.SequenceNo)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>
                            <td>
                                @item.Created.GetValueOrDefault().ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.ID })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div><!-- table-wrapper -->
    </div><!-- card -->
</div>